### find all matches
GET {{host}}:{{port}}/matches


### create match
POST {{host}}:{{port}}/matches
Content-Type: application/json

{
  "id": "ea8c63ad-a4ed-4960-b685-78442e10d345",
  "whitePlayerUsername": "careBear3000",
  "blackPlayerUsername": "lovingAndCaring4Bears",
  "outcome": "TWO_WINS",
  "timestamp": 1602329862
}

### create match java/kotlin
POST {{host}}:{{port}}/matches
Content-Type: application/json

{
  "whitePlayerUsername": "careBear3000",
  "blackPlayerUsername": "lovingAndCaring4Bears",
  "outcome": "WHITE_WINS"
}
