### find all users
GET {{host}}:{{port}}/players


### create user
POST {{host}}:{{port}}/players
Content-Type: application/json

{
  "username": "lovingAndCaring4Bears",
  "displayName": "Berthold Kehr",
  "email": "bearthold@care.de"
}

### get user by name
GET {{host}}:{{port}}/players/careBear3000

### update user
PUT {{host}}:{{port}}/players
Content-Type: application/json

{
  "id": "6cc88dc7-f334-4001-9a21-07f9b348a129",
  "username": "KenningBaerAlter",
  "displayName": "Kenning Bär",
  "email": "kenningBärRecords@carebär.de"
}

### get elo of user
GET {{host}}:{{port}}/players/carebear/elo

